INSERT IGNORE INTO vets VALUES (1, 'James', 'Carter');
INSERT IGNORE INTO vets VALUES (2, 'Helen', 'Leary');
INSERT IGNORE INTO vets VALUES (3, 'Linda', 'Douglas');
INSERT IGNORE INTO vets VALUES (4, 'Rafael', 'Ortega');
INSERT IGNORE INTO vets VALUES (5, 'Henry', 'Stevens');
INSERT IGNORE INTO vets VALUES (6, 'Sharon', 'Jenkins');

INSERT IGNORE INTO specialties VALUES (1, 'radiology');
INSERT IGNORE INTO specialties VALUES (2, 'surgery');
INSERT IGNORE INTO specialties VALUES (3, 'dentistry');
INSERT IGNORE INTO specialties VALUES (4, 'oculist');
INSERT IGNORE INTO specialties VALUES (5, 'neurologist');
INSERT IGNORE INTO specialties VALUES (6, 'oncologist');

INSERT IGNORE INTO vet_specialties VALUES (1, 6);
INSERT IGNORE INTO vet_specialties VALUES (2, 5);
INSERT IGNORE INTO vet_specialties VALUES (3, 4);
INSERT IGNORE INTO vet_specialties VALUES (4, 3);
INSERT IGNORE INTO vet_specialties VALUES (5, 2);
INSERT IGNORE INTO vet_specialties VALUES (6, 1);

INSERT IGNORE INTO types VALUES (1, 'cat');
INSERT IGNORE INTO types VALUES (2, 'dog');
INSERT IGNORE INTO types VALUES (3, 'lizard');
INSERT IGNORE INTO types VALUES (4, 'snake');
INSERT IGNORE INTO types VALUES (5, 'bird');
INSERT IGNORE INTO types VALUES (6, 'hamster');

INSERT IGNORE INTO owners VALUES (1, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT IGNORE INTO owners VALUES (2, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT IGNORE INTO owners VALUES (3, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT IGNORE INTO owners VALUES (4, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT IGNORE INTO owners VALUES (5, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT IGNORE INTO owners VALUES (6, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT IGNORE INTO owners VALUES (7, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT IGNORE INTO owners VALUES (8, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT IGNORE INTO owners VALUES (9, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT IGNORE INTO owners VALUES (10, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT IGNORE INTO pets VALUES (1, 'Leo', '2000-09-07', 1, 1);
INSERT IGNORE INTO pets VALUES (2, 'Basil', '2002-08-06', 6, 2);
INSERT IGNORE INTO pets VALUES (3, 'Rosy', '2001-04-17', 2, 3);
INSERT IGNORE INTO pets VALUES (4, 'Jewel', '2000-03-07', 2, 3);
INSERT IGNORE INTO pets VALUES (5, 'Iggy', '2000-11-30', 3, 4);
INSERT IGNORE INTO pets VALUES (6, 'George', '2000-01-20', 4, 5);
INSERT IGNORE INTO pets VALUES (7, 'Samantha', '1995-09-04', 1, 6);
INSERT IGNORE INTO pets VALUES (8, 'Max', '1995-09-04', 1, 6);
INSERT IGNORE INTO pets VALUES (9, 'Lucky', '1999-08-06', 5, 7);
INSERT IGNORE INTO pets VALUES (10, 'Mulligan', '1997-02-24', 2, 8);
INSERT IGNORE INTO pets VALUES (11, 'Freddy', '2000-03-09', 5, 9);
INSERT IGNORE INTO pets VALUES (12, 'Lucky', '2000-06-24', 2, 10);
INSERT IGNORE INTO pets VALUES (13, 'Sly', '2002-06-08', 1, 10);

INSERT IGNORE INTO visits VALUES (1, 7, '2010-03-04', 'rabies shot', 1,1);
INSERT IGNORE INTO visits VALUES (2, 8, '2011-03-04', 'rabies shot', 2,0);
INSERT IGNORE INTO visits VALUES (3, 8, '2009-06-04', 'neutered', 3,1);
INSERT IGNORE INTO visits VALUES (4, 7, '2008-09-04', 'spayed', 4,0);

INSERT IGNORE INTO users VALUES (1, 'Admin', 'Admin', 1, null, null);
INSERT IGNORE INTO users VALUES (2, 'OWNER', 'OWNER', 1, 1, null);
INSERT IGNORE INTO users VALUES (3, 'Betty', 'Davis', 1, 2, null);
INSERT IGNORE INTO users VALUES (4, 'Eduardo', 'Rodriquez', 1, 3, null);
INSERT IGNORE INTO users VALUES (5, 'Harold', 'Davis', 1, 4, null);
INSERT IGNORE INTO users VALUES (6, 'Peter', 'McTavish', 1, 5, null);
INSERT IGNORE INTO users VALUES (7, 'Jean', 'Coleman', 1, 6, null);
INSERT IGNORE INTO users VALUES (8, 'Jeff', 'Black', 1, 7, null);
INSERT IGNORE INTO users VALUES (9, 'Maria', 'Escobito', 1, 8, null);
INSERT IGNORE INTO users VALUES (10, 'David', 'Schroeder', 1, 9, null);
INSERT IGNORE INTO users VALUES (11, 'Carlos', 'Schroeder', 1, 10, null);
INSERT IGNORE INTO users VALUES (12, 'VET', 'VET', 1, null, 1);
INSERT IGNORE INTO users VALUES (13, 'Helen', 'Leary', 1, null, 2);
INSERT IGNORE INTO users VALUES (14, 'Linda', 'Douglas', 1, null, 3);
INSERT IGNORE INTO users VALUES (15, 'Rafael', 'Ortega', 1, null, 4);
INSERT IGNORE INTO users VALUES (16, 'Henry', 'Stevens', 1, null, 5);
INSERT IGNORE INTO users VALUES (17, 'Sharon', 'Jenkins', 1, null, 6);

INSERT IGNORE INTO user_role VALUES (1, 'ADMIN');
INSERT IGNORE INTO user_role VALUES (2, 'OWNER');
INSERT IGNORE INTO user_role VALUES (3, 'OWNER');
INSERT IGNORE INTO user_role VALUES (4, 'OWNER');
INSERT IGNORE INTO user_role VALUES (5, 'OWNER');
INSERT IGNORE INTO user_role VALUES (6, 'OWNER');
INSERT IGNORE INTO user_role VALUES (7, 'OWNER');
INSERT IGNORE INTO user_role VALUES (8, 'OWNER');
INSERT IGNORE INTO user_role VALUES (9, 'OWNER');
INSERT IGNORE INTO user_role VALUES (10, 'OWNER');
INSERT IGNORE INTO user_role VALUES (11, 'OWNER');
INSERT IGNORE INTO user_role VALUES (12, 'VET');
INSERT IGNORE INTO user_role VALUES (13, 'VET');
INSERT IGNORE INTO user_role VALUES (14, 'VET');
INSERT IGNORE INTO user_role VALUES (15, 'VET');
INSERT IGNORE INTO user_role VALUES (16, 'VET');
INSERT IGNORE INTO user_role VALUES (17, 'VET');
